FROM maven:3.9.7-amazoncorretto-21-debian As build
WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM maven:3.9.7-amazoncorretto-21-debian

COPY --from=build /app/APIGateway/target/APIGateway-1.0-SNAPSHOT.jar api-gateway.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/api-gateway.jar"]