FROM maven:3.9.7-amazoncorretto-21-debian As build
WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM maven:3.9.7-amazoncorretto-21-debian

COPY --from=build /app/client_application/target/client_application-1.0-SNAPSHOT.jar client-application.jar
EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/client-application.jar"]
