FROM maven:3.9.7-amazoncorretto-21-debian As build
WORKDIR /app

COPY ./APIGateway ./APIGateway
COPY ./client_application ./client_application
COPY ./server_application ./server_application
COPY ./service_registry ./service_registry
COPY ./pom.xml .

RUN mvn clean package -DskipTests

FROM maven:3.9.7-amazoncorretto-21-debian

COPY --from=build /app/client_application/target/client_application-1.0-SNAPSHOT.jar client-application.jar

ENTRYPOINT ["java", "-jar", "/client-application.jar"]
