spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: server-node
          uri: lb://server-node
          predicates:
            - Path=/api/**

      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin,*

    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080


