spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: server-node

server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
